version : '3'
services : 
  sql : 
    image : mariadb
    ports : 
      - "3307:3306"
    environment :
      MYSQL_ROOT_PASSWORD : root
    volumes :
      - ./database_init:/docker-entrypoint-initdb.d
      - ./.mysql_data:/var/lib/mysql/
  nginx :
    build :
      context : "./docker-base"
    ports :
      - "80:80"
    depends_on :
      - sql
    volumes :
      - ./code:/srv/www
      - ./logs:/LOGS